version: "2.4"
services:
  pdfviewer:
    user: torizon
    depends_on:
    - weston
    image: presentation-app:1.0.1
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
  weston:
    cap_add:
    - CAP_SYS_TTY_CONFIG
    command: --developer
    device_cgroup_rules:
    - c 4:0 rmw
    - c 4:7 rmw
    - c 13:* rmw
    - c 199:* rmw
    - c 226:* rmw
    environment:
      ACCEPT_FSL_EULA: '1'
    image: weston-custom-bg:1.1.9
    restart: always
    network_mode: host
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /dev
      target: /dev
      type: bind
    - source: /run/udev
      target: /run/udev
      type: bind
