services:
  pdfviewer:
    user: torizon
    command: evince --presentation presentation.pdf
    depends_on:
      weston:
        condition: service_started
    cap_add:
    - CAP_SYS_TTY_CONFIG
    device_cgroup_rules:
    - c 199:* rmw
    - c 226:* rmw
    restart: always
    environment:
      ACCEPT_FSL_EULA: '1'
    #image: torizon/weston-vivante@sha256:c9c846118538dee213cd740602796ca1a4eb73c5a2d6505659ce37932e40966d
    image: weston-custom-bg:dev
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /dev/galcore
      target: /dev/galcore
      type: bind
    - source: /dev/dri
      target: /dev/dri
      type: bind
  weston:
    cap_add:
    - CAP_SYS_TTY_CONFIG
    command: --developer
    device_cgroup_rules:
    - c 4:0 rmw
    - c 4:7 rmw
    - c 13:* rmw
    - c 199:* rmw
    - c 226:* rmw
    environment:
      ACCEPT_FSL_EULA: '1'
    #image: torizon/weston-vivante:$CT_TAG_WESTON_VIVANTE
    image: weston-custom-bg:dev
    network_mode: host
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /dev
      target: /dev
      type: bind
    - source: /run/udev
      target: /run/udev
      type: bind
version: '2.4'
